version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_gutendex
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gutendex-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gutendex_app
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      STATIC_ROOT: ${STATIC_ROOT}
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - gutendex-network

volumes:
  postgres_data:

networks:
  gutendex-network:
